language: python
python: 
  - "3.5"
install:
  - pip install coveralls
script: coverage run -m unittest
after_success:
  coveralls 
  
  
  [![Coverage Status](https://coveralls.io/repos/github/afwilkin/c4cs-w17-rpn/badge.svg?branch=master)](https://coveralls.io/github/afwilkin/c4cs-w17-rpn?branch=master)
